baseURL = "https://nvru.github.io/"
locale = "en-US"
title = "Null Blog"
theme = "hugo-blog-awesome"

enableEmoji = true
defaultContentLanguage = "en"
ignoreErrors = ["additional-script-loading-error"]

[params]

  # Site info
  sitename = "Null Blog"
  defaultColor = "dark"
  description = "CTF writeups, hacking notes, and walkthroughs."

  # TOC
  toc = true
  tocOpen = false

  # UI options
  goToTop = true

  # Author section 
  [params.author]
    name = "null void root"
    intro = "Pentester | CTF Player | Unix Admin"
    description = "I document my CTF machines and pentesting practice."
    avatar = "profile.png"

# Social icons
[[params.socialIcons]]
name = "codeberg"
url = "https://codeberg.org/vru"

[[params.socialIcons]]
name = "github"
url = "https://github.com/nvru"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/abdullah-keitut-880a09385"

[[params.socialIcons]]
name = "tryhackme"
url = "https://tryhackme.com/p/nvru"

[[params.socialIcons]]
name = "hackthebox"
url = "https://profile.hackthebox.com/profile/019e8425-94eb-701e-888d-be3a8a788876"

[[params.socialIcons]]
name = "hackmyvm"
url = "https://hackmyvm.eu/public/?u=vru"

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[menu]
	[[menu.main]]
	  name = "Home"
	  pageRef = "/"
	  url = "/"
	  weight = 10

	[[menu.main]]
	  name = "Walkthroughs"
	  pageRef = "walkthrough"
	  url = "/walkthrough/"
	  weight = 20

	[[menu.main]]
	  name = "Nix"
	  pageRef = "nix"
	  rl = "/nix/"
	  weight = 30

	[[menu.main]]
	  name = "Windows"
	  pageRef = "windows"
	  url = "/windows/"
	  weight = 40

	[[menu.main]]
	  name = "Techniques"
	  pageRef = "techniques"
	  url = "/techniques/"
	  weight = 50

	[[menu.main]]
	  name = "Tools"
	  pageRef = "tools"
	  url = "/tools/"
	  weight = 60

	[[menu.main]]
	  name = "About"
	  pageRef = "about"
	  url = "/about/"
	  weight = 70

